language: node_js

cache:
  directories:
    - node_modules
    - $HOME/.npm

notifications:
  email: false

node_js:
  - '7'

before_install:
  - npm i -g npm@^2.0.0
  - npm install codecov.io coveralls request

script:
  - npm run build

after_success:
  - npm run semantic-release
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
